on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy app to Contentful
    if: contains(github.ref, 'main') || contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - uses: contentful/actions-app-deploy@v1
        with:
          organization-id: ${{ secrets.6gJVHHGFZgPp5BnTlBecvq }}
          app-definition-id: ${{ secrets.d4:7b:cc:4f:8e:62:c3:de:9b:1a:f2:bb:a5:c0:8f:92:52:10:50:41:45:39:7c:5e:24:66:48:20:a3:49:c1:0f }}
          access-token: ${{ secrets.CFPAT-qpc5Juc1ISffszvsnn1VpzIdo2632-Ti7I03VmCbsNY }}
          folder: build
